### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BeastyBlacksmith** [medium-endian/randomProjections#1]
Dear Rafael,
I am thinking about reimplementing a random projection algorithm like the one implemented here and would like to know under which conditions this code can be reused or derived from.
The easiest (from my point of view) would be to add a license file to this repository.
Best regards,
Simon

**Comment by barafael** [comment]
Hi Simon,
this is really super old code. I've added an Apache 2.0 license, feel free to reuse and look around. I'd recommend taking it with a grain of salt, though :)
